import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { DefaultProviders } from "./components/default-provider";

const poppins = Poppins({ subsets: ["latin"], weight: ["600", "400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <DefaultProviders>{children}</DefaultProviders>
      </body>
    </html>
  );
}
